### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by not-ivy** [5HT2B/heartbeat#26]
Sends a message to the webhook when there is a new beat, or longest recorded absence is updated.

**Comment by l1ving** [comment]
I'm not sure about the usefulness of that. For what it's worth, the latter would get rate-limited very quickly (due to a new update happening each second).

**Comment by sourTaste000** [comment]
set like a threshold so when the last updated beat has increased an hour or a day it would use the webhook

**Comment by l1ving** [comment]
That also might not be the best use-case. Personally my longest recorded absence has only increased by a few minutes over the past year (it was 10 hours XX minutes for a few months, then 11h37m, and now it is 12h30m).

How does sending the webhook for the new longest recorded absence when the absence *ends* sound?

As in, once there is a new longest absence to report, wait until the next beat.
